# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" 
url: "https://rhymeyang.github.io"
github_username:  rhymeyang


# Settings for the plugins in the _plugins_dir folder.
plugins_dir:
  imager:
    dir_posts: assets/img/posts
  # To see language support, go to the plugin "_plugins/reading_time.rb"
  reading_time:
    locale: ch_CH

# Build local / Server
destination: _site
port: 9000
host: localhost

# [ Vendor Off ]
# Using: true | false
vendor-off: true

include: ['_pages','_general', '_docker_col']
# Build settings
markdown: kramdown
# permalink: /blog/:title/
# permalink: pretty


# paginate: 5

plugins_dir:
  - jekyll-feed

# collections:
#   docker_col:
#     output: true
#     paginate: 5
#     paginate_path: "docker_col/page:num"


# Config SASS
sass:
  sass_dir: _sass
  # style: compressed

# Add Avatar in: Sidebar or page Hello, and configure.
avatar:
  sidebar: true
  hello: false
  size:
    enable: true
    value: 165
  border:
    enable: false
    radius: 50
    value: 1

# Enable or disable icons on every website. Use:  true | false
screen:
  icons:
    enable: true


# Config plugin 'jekyll-tagging'
tag_page_layout: tag_page
tag_page_dir: blog/tags
tag_permalink_style: pretty


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - run.sh
  - sources/
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
